### PR TITLE
Tabs and other formatting

### PR DESCRIPTION
**Pull request by pthariensflame**
This brings Focus in line with the TypeLift standards.  :)

### CODE REVIEW

**Comment by CodaFi** [comment]
:+1:

Now format all of Aquifer 😈

**Comment by CodaFi** [comment]
Oh, While I have you, can you remove the version variables from our public header?

**Comment by pthariensflame** [comment]
Sure!

**Comment by pthariensflame** [comment]
And I'll format Aquifer once I've finished formatting Swiftz.  :angel:

**Comment by CodaFi** [comment]
Good to go.

**Comment by CodaFi** [comment]
:boat:

**Pull request merged**
