### PR TITLE
[WIP] Partial Lenses

### PR DESCRIPTION
**Pull request by pthariensflame**

### CODE REVIEW

**Comment by pthariensflame** [comment]
@CodaFi We need to talk about how dependencies work among the TypeLift frameworks.

In order to implement partial lenses (and, in future, traversables, etc.), I need Focus to depend on Swiftx at the very least.  However, Aquifer depends on both Swiftz _and_ Focus.  The end result of the way I was going to do this was that Aquifer became uncompilable, because Focus imported Swiftx, which declared `Either`, and Swiftz also declared `Either`, and the two `Either`s weren't recognized as the same type (because they were declared in different modules).  I don't see a way we could possibly solve this issue without completely reworking how Carthage stores and uses dependencies, at least if we stick to the current way of doing things here.

Any ideas?

**Comment by CodaFi** [comment]
Depend on Operadics always, use Swiftx to pick and choose which files you want (like how Swiftz does it but with a subset of files).

**Comment by pthariensflame** [comment]
That still causes duplication, and Aquifer will see two `Either`s (from `Focus` and from `Swiftz`).

**Comment by CodaFi** [comment]
Then Aquifer needs to get off Swiftz as much as possible.

**Comment by pthariensflame** [comment]
:P

Ok, but even if I only depend on Swiftx, I'll _still_ have duplication.

**Comment by pthariensflame** [comment]
Oh, also, this doesn't address the case where one of our users wants to use a whole bunch of our libraries at once.  Then they might get as many as _four different definitions of `Either`_, all of which are exactly identical, and none of which are compatible with each other.

**Comment by CodaFi** [comment]
Then there needs to be some way of making these libraries act as Matryoshka Dolls that can be scaled up or down based on the need for abstractions.  As for the matter of multiple definitions, in a library like this the only option I can think of to fix the duplication is simply inlining one copy of Swiftx with the framework.

**Comment by CodaFi** [comment]
It would also be cool to setup a repository that was just a README explaining how the various frameworks interact and work with whatever we come up with here.

**Comment by pthariensflame** [comment]
As long as we have a total ordering among the frameworks, the current solution works (albeit clunkily).  The only time we get problems is when the totality of the order breaks, and we end up with a non-virtual diamond dependency.

**Comment by CodaFi** [comment]
Mhm.  So that means Focus either has to wind up absorbing Swiftz or it has to get off it entirely like SwiftCheck and Concurrent do.  To do the former would be a little ridiculous, and the latter would sacrifice a large amount of features of the library

**Comment by pthariensflame** [comment]
Yup.  Having stated it in terms of non-virtual inheritance, I had the idea that maybe we could virtualize it.  Is there a way to tell Carthage to do that?

**Comment by CodaFi** [comment]
It's All Git Eventually, so probably not.

**Comment by pthariensflame** [comment]
Hm…

I'm actually not so sure it isn't possible, given judicious application of symlinks.  Let me experiment for a while.

**Pull request closed without merging**
