### PR TITLE
Update SwiftCheck dependency

### PR DESCRIPTION
**Pull request by pthariensflame**
This is the only thing we need to do to make Focus play nicely with Xcode 7 beta 5.

### CODE REVIEW

**Comment by CodaFi** [comment]
:+1:

**Comment by pthariensflame** [comment]
@CodaFi You'll have to merge this, unless you want to give me write access.  :)

**Comment by CodaFi** [comment]
How do you still not have that?  Let me see if I can alter your permissions real quick.

**Comment by CodaFi** [comment]
Also :boat:

**Comment by pthariensflame** [comment]
@CodaFi _cu̇s ȧdʹruʹȧ̇n_

:D

**Pull request merged**
