### PR TITLE
Add Setter implementation

### PR DESCRIPTION
**Pull request by r-peck**
Let me know if there is a different approach you had in mind. I could also use some feedback on making the documentation summary more complete and clear.

### CODE REVIEW

**Comment by CodaFi** [comment]
Thanks for the pull request!  

I'm a little hesitant about this change in general.  A `Setter` is supposed to generalize `fmap`, but we can't apply a Functor constraint to any part of this without HKTs, nor do we get the benefits of a fully general `over` from this.  If this were to merged, we would have to make it clear that this is either `ASetter` or `Setter` with the `Identity` monad inlined.

**Comment by CodaFi** [comment]
Thanks for the pull request.  I think this looks pretty good as-is.  If you can get the tests to pass (looks like you just didn't include a file or two in a target) I think it's ready to merge.

**Comment by r-peck** [comment]
Fixed the target inclusion issues.

**Comment by CodaFi** [comment]
Alright, thanks again!

**Comment by CodaFi** [comment]
:boat:

**Pull request merged**
